query listProjects($filters: listProjectsInput) {
  listProjects(filters: $filters) {
    projects{
        updated
        status
        pubId
        name
        followed
        feedback
        entity
        edited
        createdAt
        commented
        requests
    }
    total
  }
}
